name: jarvis
description: JARVIS - shaxsiy AI yordamchi
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.5
  audioplayers: ^6.1.0
  local_auth: ^2.3.0
  android_intent_plus: ^5.2.0
  permission_handler: ^11.3.1
  record: ^6.0.0
  path_provider: ^2.1.4
  another_telephony: ^0.4.1
  notification_listener_service: ^1.0.0
flutter:
  uses-material-design: true
